/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SolarRoiIndexImport } from './routes/solar-roi/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SolarRoiIndexRoute = SolarRoiIndexImport.update({
  id: '/solar-roi/',
  path: '/solar-roi/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/solar-roi/': {
      id: '/solar-roi/'
      path: '/solar-roi'
      fullPath: '/solar-roi'
      preLoaderRoute: typeof SolarRoiIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/solar-roi': typeof SolarRoiIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/solar-roi': typeof SolarRoiIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/solar-roi/': typeof SolarRoiIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/solar-roi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/solar-roi'
  id: '__root__' | '/' | '/solar-roi/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SolarRoiIndexRoute: typeof SolarRoiIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SolarRoiIndexRoute: SolarRoiIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/solar-roi/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/solar-roi/": {
      "filePath": "solar-roi/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
